config/routes.rb
      resources :palletizing_pallets do
        collection do
          get :print
        end
      end
  end

  resources :palletizing_pallets do
    collection do
      get :query_pallet
      get :new_output_box
      get :output_box
      get :new_input_house
      get :confirm_input_house
      get :input_house
      get :switch_move_pallet
    end
    member do
      get :by_nfe
      get :output_house
      get :new_input_box
      get :input_box
    end
  end
  # match "/palletizing_pallets/query_pallet", :controller => "palletizing_pallets", :action => "query_pallet", via: [:get]

  # resources :breakdown_nfe_xmls

  resources :conference_breakdowns do
    member do
      get :finish
    end
  end

  resources :conference_items do
    member do
      patch :update
    end
  end

  resources :conferences do
    member do
      get :correction
      get :finish_conference
      post :add_item
      delete :destroy_item
    end
  end

  resources :addresses_houses do
    collection do
      get :do_occupe
      get :do_vacate
      get :houses
      post :generator
    end
  end
  resources :houses do

  end
  resources :floors do
    collection do
      get :get_floors_by_street
    end
  end
  resources :streets do
    collection do
      get :get_streets_by_deposit
    end
  end

  resources :deposits do
    collection do
      get :get_deposits_by_warehouse
    end
  end
  resources :warehouses
  resources :checkins do
    member do
      get :checkout
    end
    collection do
      get :search
      get :sup_input
      get :sup_boarding
    end
  end
  resources :driver_restrictions do
    member do
      get :unlock
    end
  end

  resources :vehicle_restrictions do
    member do
      get :unlock
    end
  end

  resources :notifications do
    post :mark_as_read, on: :collection
    get :mark_as_read, on: :member
  end

  resources :brokers

  resources :insurers do
    resources :table_insurances
    resources :policie_insurances
  end

  resources :notfis, only: [:index, :show] do
    collection do
      get :search
    end
  end

  resources :file_edis, only: [:index, :show] do
  collection do
      get :search
      get :select
      post :upload
    end
  end

  resources :edi_occurrences, only: [:index] do
    collection do
      get :search
      get :generate_file
    end
  end

  resources :clients_pallets

  match "/phones", :controller => "static_pages", :action => "phones", via: [:get]
  match "/table_freights/get_calc_freight_minimum", :controller => "table_freights", :action => "get_calc_freight_minimum", via: [:get]
  match '/calculate_liquidity', :controller => 'static_pages', :action => 'calculate_liquidity', via: [:get, :post]
  match "/stretch_routes/get_stretch_route_by_id", :controller => "stretch_routes", :action => "get_stretch_route_by_id", via: [:get]
  match "/stretch_routes/get_stretch_route_by_state", :controller => "stretch_routes", :action => "get_stretch_route_by_state", via: [:get]
  match "/stretch_routes/get_stretch_route_by_state_source_ant_target", :controller => "stretch_routes", :action => "get_stretch_route_by_state_source_ant_target", via: [:get]

  resources :table_freights do
    collection do
      get :calculate_liquidity
    end
  end

  resources :table_icms do
    collection do
      get :search
    end
  end

  resources :antts_vehicles

  resources :antts do
    resources :antts_vehicles
  end

  resources :micro_regions do
    resources :micro_regions_cities
  end

  resources :meetings do
    resources :subjects do
      resources :subject_answers
    end
  end

  resources :action_inspectors, only: [:index, :edit, :update]

  resources :advance_moneys

  match "/get_stretch_routes_from_client_cnpj", :controller => "stretch_routes", :action => "get_stretch_routes_from_client_cnpj", via: [:get]
  match "/get_client_table_price_of_by_client_cnpj_and_stretch_route", :controller => "client_table_prices", :action => "get_client_table_price_of_by_client_cnpj_and_stretch_route", via: [:get]
  match "/get_client_table_price_of_client", :controller => "client_table_prices", :action => "get_client_table_price_of_client", via: [:get]
  match "/get_client_table_price_of_client_service", :controller => "client_table_prices", :action => "get_client_table_price_of_client_service", via: [:get]

  resources :nature_freights

  resources :segments

  resources :promoters

  resources :stretch_routes

  resources :stretches

  resources :tasks do
    collection do
      get :search
    end
    member do
      get :start
      get :finish
      post :add_tasks_users
    end
  end

  match "list_input_scheduling" => "input_controls#list_input_scheduling",  via: [:get]
  match "list_ordem_service_scheduling" => "ordem_services#list_ordem_service_scheduling",  via: [:get]

  resources :companies, only: [:edit, :update, :show]

  resources :config_systems

  resources :client_representatives

  resources :representatives

  resources :offer_drivers do
    member do
      get :confirmed
      get :reject_form
      patch :reject
      get :noshow
      get :nonsuit
      get :reject_observation
    end
  end

  resources :offer_charges do
    collection do
      get :search
    end
  end

  resources :breakdowns

  resources :schedulings do
    collection do
      get :search
    end
  end

  #match :stock_equipaments, :as => :stock_equipaments,  via: [:get]
  match :stock_equipaments,  to: 'stock_equipaments#index',  via: [:get]

  resources :transfer_equipaments, only: [:new] do
    collection do
      post :create
    end
  end

  resources :control_pallet_internals do
    member do
      get :term_pallet
    end
  end

  resources :direct_charges do
    member do
      get :finish_typing
      get :select_nfe
      post :create_ordem_service
      get :add_nfe_xml
      put :attach_xml
    end
  end

  resources :input_controls do
    resources :breakdowns
    resources :breakdown_input_controls do
      get :product
      post :update_product, on: :collection
    end

    resources :breakdown_nfe_xmls

    # resources :nfe_xmls do
    #   resources :breakdown_nfe_xmls
    # end

    resources :conferences do
      resources :conference_breakdowns do
        get :finish
      end
      resources :conference_items
      collection do
        get :approved_last
      end
    end
    member do
      get :admin_show
      get :analize_and_finish
      get :start_conference
      get :review_conference
      get :items
      # get :has_avaria
      get :update_has_avaria
      get :report_team
      put :update_report_team
      get :documents
      patch :documents, to: 'input_controls#documents_upload'
      delete :documents, to: 'input_controls#documents_destroy'
      get 'select_nfe'
      get 'select_pallets'
      post 'create_ordem_service'
      post 'create_stok_pallets'
      get 'finish_typing'
      get 'quitter'
      get :comments
      get :question
      get :printing
      get :print_blind
      get :print_products
      get :print_products_conference
      get :tag
      get :start
      patch :update_start
      get :received
      patch :confirm_received
      get :list_nfe_xmls
      # patch :confirm_qtde_pallets
      get :reschedule
      patch :update_reschedule
      get :add_nfe_xml
      put :attach_xml
    end
    collection do
      get :sup_search
      get :search
      get :oper
      get :sup
      get :admin
    end

    get :received_weight, on: :collection
    get :received_weight_search, on: :collection

    resources :palletizings

  end

  #match '/select_xml_nfe_new_ordem_services', :controller => 'new_ordem_services', :action => 'select_xml_nfe', via: [:get, :post]
  resources :new_creation_ordem_services do
    get :select_xml_nfe, on: :collection
    post :process_xml_nfe, on: :collection
  end

  resources :sealingwaxes

  resources :boardings do
    #resources :sealingwaxes
    resources :breakdown_boardings
    member do
      get :report_team
      put :update_report_team
      get :print
      get :comments
      get :request_pallet
      post :requisition
      get :letter_freight
      get :confirmed
      patch :update_confirmed
      get :start
      patch :update_start
      get :checkin
      patch :update_checkin
      get :detail
      post :request_payment
      get :declined
    end
    collection do
      get :search
      get :sup_search
      get :oper
      get :sup
    end
    resources :boarding_items do
      post :update_row_order, on: :collection
    end
    resources :boarding_vehicles do
      #code
    end
    #match :cancellation, :as => :cancellation, :via => [:get, :put]
    get :selection_shipment_search, on: :collection
    get :payment_discharge_client, on: :collection

  end

  resources :boarding_items do
    post :update_row_order, on: :collection
    match :update_status, :as => :update_status, :via => [:get, :put]
  end

  resources :lower_payables, only: [:destroy] do
    get :quitter, on: :member
  end
  resources :lower_receivables, only: [:destroy] do
    get :quitter, on: :member
  end

  resources :account_receivables do
    member do
      get 'lower'
      post 'pay'
    end
    get :received_driver, on: :collection
    collection do
      get :search
      post :lower_all
    end
  end

  resources :account_payables do
    member do
      get 'lower'
      post 'pay'
      get :send_mail
      #delete 'lower_payable/id'
    end
    collection do
      get 'cost_centers'
      get :search
    end
  end

  get '/print_inventory/:id', to: 'reports#print_inventory', as: 'print_inventory'
  get '/print_contract/:id', to: 'reports#print_contract', as: 'print_contract'
  #get '/print_boarding/:id', to: 'reports#print_boarding', as: 'print_boarding'
  get '/print_billing/:id', to: 'reports#print_billing', as: 'print_billing'

  match 'selection_pallet' => "control_pallets#selection_pallet",  via: [:get]
  match 'selection_pallet' => "control_pallets#selection_pallet",  via: [:get]

app/models/antt.rb
class Antt < ActiveRecord::Base
	validates :rntrc, presence: true, numericality: { only_integer: true }
  validates :cpf_cnpj, presence:true
  validates :name, presence: true
  validates :date_expiration, presence: true

  #has_and_belongs_to_many :vehicles

  has_many :antts_vehicles, class_name: "AnttsVehicles"

	has_many :vehicles, through: :antts_vehicles
end

app/controllers/antts_controller.rb
class AnttsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_antt, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  respond_to :html

  def index
    @antts = Antt.all
    respond_with(@antts)
  end

  def show
    @antts_vehicles = AnttsVehicles.new
    respond_with(@antt)
  end

  def new
    @antt = Antt.new
    respond_with(@antt)
  end

  def edit
  end

  def create
    @antt = Antt.new(antt_params)
    @antt.save
    respond_with(@antt)
  end

  def update
    @antt.update(antt_params)
    respond_with(@antt)
  end

  def destroy
    @antt.destroy
    respond_with(@antt)
  end

  private
    def set_antt
      @antt = Antt.find(params[:id])
    end

    def antt_params
      params.require(:antt).permit(:rntrc, :cpf_cnpj, :name, :date_expiration)
    end
end

app/helpers/antts_helper.rb
module AnttsHelper
end

app/views/antts/_antts_vehicle_fields.html.erb
  <div class="form-group">
    <%= f.label :vehicle_id, "Placa" %>
    <%= f.text_field :vehicle_id, class: "form-control", style: 'text-transform:uppercase' %>
  </div>

  <div id="vehicle_place_result">

  </div>

 <script type="text/javascript">
  $(document).ready(function() {
   $("#antt_antts_vehicles_vehicle_id").focusout(function() {
      var place = $('#antt_antts_vehicles_vehicle_id').val();
      console.log(place);
      $.ajax({
        type: "GET",
        data: {place: place},
        dataType : 'html',
        url: '/vehicles/get_vehicle_by_place',
				error: function(jqXHR, textStatus, errorThrown) {
					console.log(jqXHR.status)
          if (jqXHR.status == 404) {
          	$('#vehicle_place_result').empty();
            $('#vehicle_place_result').append("<%= j (content_tag(:div, content_tag(:p, 'Veiculo nao encontrado.'), class: 'alert alert-danger')) %>");
          }
        },
        success: function(data){
          $('#vehicle_place_result').empty();
        },
      });
    });
  });
</script>

<script type="text/javascript">

  function forceInputUppercase(e)
  {
    var start = e.target.selectionStart;
    var end = e.target.selectionEnd;
    e.target.value = e.target.value.toUpperCase();
    e.target.setSelectionRange(start, end);
  }

  document.getElementById("antt_antts_vehicles_vehicle_id").addEventListener("keyup", forceInputUppercase, false);

</script>

app/views/antts/_form.html.erb
<%= form_for(@antt) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :rntrc %><br>
    <%= f.text_field :rntrc, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :cpf_cnpj %><br>
    <%= f.text_field :cpf_cnpj, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>  

  <div class="form-group">
    <%= f.label :date_expiration %><br>
    <%= f.text_field :date_expiration, class: "form-control data", value: date_br(@antt.date_expiration) %>
  </div>

  <div class="form-group">
    <%= f.submit "Salvar", class: "btn btn-blue" %>
    <%= link_to "Exibir",  antt_path(@antt), class: "btn btn-info" if !@antt.new_record? %>
    <%= link_to "Listar Todos", antts_path, class: "btn btn-default" %>
  </div>

<% end %>

app/views/antts/edit.html.erb
<h1>Editing antt</h1>

<%= render 'form' %>

app/views/antts/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Listagem de ANTT</div>
  <div class="panel-body">
    <%= link_to 'New Antt', new_antt_path, class: "btn btn-blue btn-lg btn-block" %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Rntrc</th>
            <th>Cpf cnpj</th>
            <th>Nome</th>
            <th>Date expiration</th>
            <th colspan="3">Opções</th>
          </tr>
        </thead>

        <tbody>
          <% @antts.each do |antt| %>
            <tr>
              <td><%= antt.rntrc %></td>
              <td><%= antt.cpf_cnpj %></td>
              <td><%= antt.name %></td>
              <td><%= date_br antt.date_expiration %></td>
              <td><%= link_to 'Show', antt, class: "btn btn-info btn-sm" %></td>
              <td><%= link_to 'Edit', edit_antt_path(antt), class: "btn btn-blue btn-sm" %></td>
              <td><%= link_to 'Destroy', antt, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>    
  </div>
</div>

app/views/antts/new.html.erb
<h1>New antt</h1>

<%= render 'form' %>

app/views/antts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Dados da ANTT
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <div class="panel panel-default">

          <div class="panel panel-default">

            <div class="panel-body">

              <p>
                <strong>Rntrc:</strong>
                <%= @antt.rntrc %>
              </p>

              <p>
                <strong>Cpf cnpj:</strong>
                <%= @antt.cpf_cnpj %>
              </p>

              <p>
                <strong>Nome:</strong>
                <%= @antt.name %>
              </p>

              <p>
                <strong>Date expiration:</strong>
                <%= date_br @antt.date_expiration %>
              </p>

            </div>
          </div>

        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Veículos
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <%#= link_to '[+] Veículos', '#new_type_service', 'data-toggle' => 'modal', class: "btn btn-success btn-sm" %>
        <%= link_to '[+] Veículos', '#new_type_service', 'data-toggle' => 'modal', class: "btn btn-success btn-sm" %>

        <div id="antts_vehicles_list">
          <%#= render 'shared/show_vehicle_compact', object: @antt %>
          <%= render 'antts_vehicles/antts_vehicles', object: @antt.antts_vehicles %>
        </div>

        <div class="modal fade" id="new_type_service" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Adicionar Veículo: </h4>
              </div>
              <div class="modal-body">
                <%= render 'antts_vehicles/form_js', modal: true %>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>


      </div>
    </div>
  </div>

<!-- Fim collapse  -->
</div>

<div class="form-group">
  <%= link_to 'Editar', edit_antt_path(@antt), class: "btn btn-blue" %>
  <%= link_to 'Voltar', antts_path, class: "btn btn-default" %>
</div>