config/routes.rb
      get :query_pallet
      get :new_output_box
      get :output_box
      get :new_input_house
      get :confirm_input_house
      get :input_house
      get :switch_move_pallet
    end
    member do
      get :by_nfe
      get :output_house
      get :new_input_box
      get :input_box
    end
  end
  # match "/palletizing_pallets/query_pallet", :controller => "palletizing_pallets", :action => "query_pallet", via: [:get]

  # resources :breakdown_nfe_xmls

  resources :conference_breakdowns do
    member do
      get :finish
    end
  end

  resources :conference_items do
    member do
      patch :update
    end
  end

  resources :conferences do
    member do
      get :correction
      get :finish_conference
      post :add_item
      delete :destroy_item
    end
  end

  resources :addresses_houses do
    collection do
      get :do_occupe
      get :do_vacate
      get :houses
      post :generator
    end
  end
  resources :houses do

  end
  resources :floors do
    collection do
      get :get_floors_by_street
    end
  end
  resources :streets do
    collection do
      get :get_streets_by_deposit
    end
  end

  resources :deposits do
    collection do
      get :get_deposits_by_warehouse
    end
  end
  resources :warehouses
  resources :checkins do
    member do
      get :checkout
    end
    collection do
      get :search
      get :sup_input
      get :sup_boarding
    end
  end
  resources :driver_restrictions do
    member do
      get :unlock
    end
  end

  resources :vehicle_restrictions do
    member do
      get :unlock
    end
  end

  resources :notifications do
    post :mark_as_read, on: :collection
    get :mark_as_read, on: :member
  end

  resources :brokers

  resources :insurers do
    resources :table_insurances
    resources :policie_insurances
  end

  resources :notfis, only: [:index, :show] do
    collection do
      get :search
    end
  end

  resources :file_edis, only: [:index, :show] do
  collection do
      get :search
      get :select
      post :upload
    end
  end

  resources :edi_occurrences, only: [:index] do
    collection do
      get :search
      get :generate_file
    end
  end

  resources :clients_pallets

  match "/phones", :controller => "static_pages", :action => "phones", via: [:get]
  match "/table_freights/get_calc_freight_minimum", :controller => "table_freights", :action => "get_calc_freight_minimum", via: [:get]
  match '/calculate_liquidity', :controller => 'static_pages', :action => 'calculate_liquidity', via: [:get, :post]
  match "/stretch_routes/get_stretch_route_by_id", :controller => "stretch_routes", :action => "get_stretch_route_by_id", via: [:get]
  match "/stretch_routes/get_stretch_route_by_state", :controller => "stretch_routes", :action => "get_stretch_route_by_state", via: [:get]
  match "/stretch_routes/get_stretch_route_by_state_source_ant_target", :controller => "stretch_routes", :action => "get_stretch_route_by_state_source_ant_target", via: [:get]

  resources :table_freights do
    collection do
      get :calculate_liquidity
    end
  end

  resources :table_icms do
    collection do
      get :search
    end
  end

  resources :antts_vehicles

  resources :antts do
    resources :antts_vehicles
  end

  resources :micro_regions do
    resources :micro_regions_cities
  end

  resources :meetings do
    resources :subjects do
      resources :subject_answers
    end
  end

  resources :action_inspectors, only: [:index, :edit, :update]

  resources :advance_moneys

  match "/get_stretch_routes_from_client_cnpj", :controller => "stretch_routes", :action => "get_stretch_routes_from_client_cnpj", via: [:get]
  match "/get_client_table_price_of_by_client_cnpj_and_stretch_route", :controller => "client_table_prices", :action => "get_client_table_price_of_by_client_cnpj_and_stretch_route", via: [:get]
  match "/get_client_table_price_of_client", :controller => "client_table_prices", :action => "get_client_table_price_of_client", via: [:get]
  match "/get_client_table_price_of_client_service", :controller => "client_table_prices", :action => "get_client_table_price_of_client_service", via: [:get]

  resources :nature_freights

  resources :segments

  resources :promoters

  resources :stretch_routes

  resources :stretches

  resources :tasks do
    collection do
      get :search
    end
    member do
      get :start
      get :finish
      post :add_tasks_users
    end
  end

  match "list_input_scheduling" => "input_controls#list_input_scheduling",  via: [:get]
  match "list_ordem_service_scheduling" => "ordem_services#list_ordem_service_scheduling",  via: [:get]

  resources :companies, only: [:edit, :update, :show]

  resources :config_systems

  resources :client_representatives

  resources :representatives

  resources :offer_drivers do
    member do
      get :confirmed
      get :reject_form
      patch :reject
      get :noshow
      get :nonsuit
      get :reject_observation
    end
  end

  resources :offer_charges do
    collection do
      get :search
    end
  end

  resources :breakdowns

  resources :schedulings do
    collection do
      get :search
    end
  end

  #match :stock_equipaments, :as => :stock_equipaments,  via: [:get]
  match :stock_equipaments,  to: 'stock_equipaments#index',  via: [:get]

  resources :transfer_equipaments, only: [:new] do
    collection do
      post :create
    end
  end

  resources :control_pallet_internals do
    member do
      get :term_pallet
    end
  end

  resources :direct_charges do
    member do
      get :finish_typing
      get :select_nfe
      post :create_ordem_service
      get :add_nfe_xml
      put :attach_xml
    end
  end

  resources :input_controls do
    resources :breakdowns
    resources :breakdown_input_controls do
      get :product
      post :update_product, on: :collection
    end

    resources :breakdown_nfe_xmls

    # resources :nfe_xmls do
    #   resources :breakdown_nfe_xmls
    # end

    resources :conferences do
      resources :conference_breakdowns do
        get :finish
      end
      resources :conference_items
      collection do
        get :approved_last
      end
    end
    member do
      get :admin_show
      get :analize_and_finish
      get :start_conference
      get :review_conference
      get :items
      # get :has_avaria
      get :update_has_avaria
      get :report_team
      put :update_report_team
      get :documents
      patch :documents, to: 'input_controls#documents_upload'
      delete :documents, to: 'input_controls#documents_destroy'
      get 'select_nfe'
      get 'select_pallets'
      post 'create_ordem_service'
      post 'create_stok_pallets'
      get 'finish_typing'
      get 'quitter'
      get :comments
      get :question
      get :printing
      get :print_blind
      get :print_products
      get :print_products_conference
      get :tag
      get :start
      patch :update_start
      get :received
      patch :confirm_received
      get :list_nfe_xmls
      # patch :confirm_qtde_pallets
      get :reschedule
      patch :update_reschedule
      get :add_nfe_xml
      put :attach_xml
    end
    collection do
      get :sup_search
      get :search
      get :oper
      get :sup
      get :admin
    end

    get :received_weight, on: :collection
    get :received_weight_search, on: :collection

    resources :palletizings

  end

  #match '/select_xml_nfe_new_ordem_services', :controller => 'new_ordem_services', :action => 'select_xml_nfe', via: [:get, :post]
  resources :new_creation_ordem_services do
    get :select_xml_nfe, on: :collection
    post :process_xml_nfe, on: :collection
  end

  resources :sealingwaxes

  resources :boardings do
    #resources :sealingwaxes
    resources :breakdown_boardings
    member do
      get :report_team
      put :update_report_team
      get :print
      get :comments
      get :request_pallet
      post :requisition
      get :letter_freight
      get :confirmed
      patch :update_confirmed
      get :start
      patch :update_start
      get :checkin
      patch :update_checkin
      get :detail
      post :request_payment
      get :declined
    end
    collection do
      get :search
      get :sup_search
      get :oper
      get :sup
    end
    resources :boarding_items do
      post :update_row_order, on: :collection
    end
    resources :boarding_vehicles do
      #code
    end
    #match :cancellation, :as => :cancellation, :via => [:get, :put]
    get :selection_shipment_search, on: :collection
    get :payment_discharge_client, on: :collection

  end

  resources :boarding_items do
    post :update_row_order, on: :collection
    match :update_status, :as => :update_status, :via => [:get, :put]
  end

  resources :lower_payables, only: [:destroy] do
    get :quitter, on: :member
  end
  resources :lower_receivables, only: [:destroy] do
    get :quitter, on: :member
  end

  resources :account_receivables do
    member do
      get 'lower'
      post 'pay'
    end
    get :received_driver, on: :collection
    collection do
      get :search
      post :lower_all
    end
  end

  resources :account_payables do
    member do
      get 'lower'
      post 'pay'
      get :send_mail
      #delete 'lower_payable/id'
    end
    collection do
      get 'cost_centers'
      get :search
    end
  end

  get '/print_inventory/:id', to: 'reports#print_inventory', as: 'print_inventory'
  get '/print_contract/:id', to: 'reports#print_contract', as: 'print_contract'
  #get '/print_boarding/:id', to: 'reports#print_boarding', as: 'print_boarding'
  get '/print_billing/:id', to: 'reports#print_billing', as: 'print_billing'

  match 'selection_pallet' => "control_pallets#selection_pallet",  via: [:get]
  match 'selection_pallet' => "control_pallets#selection_pallet",  via: [:get]
  match 'generate_ordem_service' => "control_pallets#generate_ordem_service",  via: [:post]

app/models/meeting.rb
class Meeting < ActiveRecord::Base
	has_many :subjects

  has_many :assets, as: :asset, dependent: :destroy
  accepts_nested_attributes_for :assets, allow_destroy: true, reject_if: :all_blank	
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_meeting, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  respond_to :html

  def index
    @meetings = Meeting.all
  end

  def show
    
  end

  def new
    @meeting = Meeting.new
    
  end

  def edit
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.created_user_id = current_user.id
    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, flash: { success: "Meeting was successfully created." } }
        format.json { render action: 'show', status: :created, location: @meeting }
      else
        format.html { render action: 'new' }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      @meeting.updated_user_id = current_user.id
      if @meeting.update(meeting_params)
        format.html { redirect_to @meeting, flash: { success: 'Meeting was successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @meeting.destroy
    respond_with(@meeting)
  end

  private
    def set_meeting
      @meeting = Meeting.find(params[:id])
    end

    def meeting_params
      params.require(:meeting).permit(:date_event, :time_event, :local, :summoned, :facilitator, :secretary, :objective,
        assets_attributes: [:asset, :id, :_destroy]
        
        )
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_data_meeting.html.erb
<p>
  <strong>Data Reunião:</strong>
  <%= date_br(@meeting.date_event) %> as <%= time_br(@meeting.time_event) %>
</p>

<p>
  <strong>Local:</strong>
  <%= @meeting.local %>
</p>

<p>
  <strong>Convocado por:</strong>
  <%= @meeting.summoned %>
</p>

<p>
  <strong>Facilitador:</strong>
  <%= @meeting.facilitator %>
</p>

<p>
  <strong>Secretario(a):</strong>
  <%= @meeting.secretary %>
</p>

<p>
  <strong>Objective:</strong>
  <pre><%= @meeting.objective %></pre>
</p>

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <div class="form-group">
    <%= f.label :date_event,"Data" %><br>
    <% if @meeting.new_record? %>
      <%= f.text_field :date_event, class: "form-control data" %>
    <% else %>
      <%= f.text_field :date_event, class: "form-control data", value: date_br(@meeting.date_event)  %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :time_event,"Hora" %><br>
    <%= f.text_field :time_event, class: "form-control time" %>
  </div>  
  <div class="form-group">
    <%= f.label :local, "Local" %><br>
    <%= f.text_field :local, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :summoned, "Convocado por" %><br>
    <%= f.text_field :summoned, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :facilitator, "Facilitador" %><br>
    <%= f.text_field :facilitator, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :secretary, "Secretario(a)" %><br>
    <%= f.text_field :secretary, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :objective, "Objetivo" %><br>
    <%= f.text_area :objective, class: "form-control" %>
  </div>

  <h3>Documentos</h3> 
  <div id="documents">
    <div class="items">
      <%= f.nested_fields_for :assets do |f| 
        render 'shared/asset', f: f
      end  -%>
    </div>
      <br /> <a href="#" class="btn btn-success btn-sm add">[+] Documento</a>  
  </div>

  <hr />
  
  <div class="form-group">
    <%= f.submit "Salvar", class: "btn btn-blue" %>
    <%= link_to "Exibir",  meeting_path(@meeting), class: "btn btn-info" if !@meeting.new_record? %>
    <%= link_to "Listar Todos", meetings_path, class: "btn btn-default" %>
  </div>

<% end %>

app/views/meetings/_header.html.erb
<tr>
  <th>Data</th>
  <th>Hora</th>
  <th>Local</th>
  <th>Convocado</th>
  <th>Facilitador</th>
  <th>Secretario(a)</th>
  <th colspan="3"></th>
</tr>

app/views/meetings/_meeting.html.erb
<tr>
  <td><%= date_br(meeting.date_event) %></td>
  <td><%= time_br(meeting.time_event) %></td>
  <td><%= meeting.local %></td>
  <td><%= meeting.summoned %></td>
  <td><%= meeting.facilitator %></td>
  <td><%= meeting.secretary %></td>
  <td><%= link_to 'Show', meeting, class: "btn btn-info btn-sm" %></td>
  <td><%= link_to 'Edit', edit_meeting_path(meeting), class: "btn btn-blue btn-sm" %></td>
</tr>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

app/views/meetings/index.html.erb
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">

  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingEleven">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseEleven" aria-expanded="false" aria-controls="collapseEleven">
          Pesquisar
        </a>
      </h4>
    </div>
    <div id="collapseEleven" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingEleven">
      <div class="panel-body">

      <%#= render "form_search" %>

    </div>
  </div>

</div>

<div class="panel panel-default">
  <div class="panel-heading">Listing meetings</div>
  <div class="panel-body">

    <%= link_to 'New Meeting', new_meeting_path, class: "btn btn-blue btn-sm btn-block" %>
    <div class="table-responsive">
      
        <div id="result_scheduling">

        <table class="table table-striped" id="table_offer_drivers">
          <thead>
            <%= render 'header' %>
          </thead>

          <tbody>
            <%= render @meetings %>
          </tbody>

        </table>
      </div>

    </div>    
  </div>
</div>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render 'form' %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Dados da Reunião:
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <div class="panel panel-default">

          <div class="panel panel-default">

            <div class="panel-body"> 
              <%= render 'data_meeting' %>
            </div>
          </div>
        
        </div>
      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Assuntos Abordados
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <%= link_to '[+] Novo Assunto', new_meeting_subject_path(@meeting), class: "btn btn-success btn-xs" %>      

        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Assunto</th>
                <th>Duração</th>
                <th>Responsavel</th>
                <th>Options</th>
              </tr>
            </thead>

            <tbody>
              <% @meeting.subjects.each do |subject| %>
                <tr>
                  <td><%= subject.title %></td>
                  <td><%= time_br subject.time_meeting %> </td>
                  <td><%= subject.responsible %></td>
                  <td><%= link_to 'Exibir', meeting_subject_path(@meeting, subject), class: "btn btn-info btn-xs" %></td>
                  <td><%= link_to '[+] Plano de Ação', new_meeting_subject_subject_answer_path(@meeting, subject), class: "btn btn-blue btn-xs" %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>    

      </div>
    </div>
  </div>

  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Documentos
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">

        <div class="panel-body"> 
          <%= render 'shared/document', object: @meeting %>
        </div>

    </div>
  </div>

<!-- Fim collapse  --> 
</div>

<div class="form-group">
  <%= link_to 'Editar', edit_meeting_path(@meeting), class: "btn btn-blue" %>
  <%= link_to 'Listar Todos', meetings_path, class: "btn btn-default" %>
</div>