config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  resources :nfe_xml_devolutions do
    member do
      post :xml_process
    end
  end

  resources :devolutions
  get 'palletizing_pallet_product/index'

  resources :palletizings do
    collection do
      get :select_input_control
    end
    member do
      get :view_mode_change
      patch :update_view_mode
    end
      resources :palletizing_pallets do
        collection do
          get :print
        end
      end
  end

  resources :palletizing_pallets do
    collection do
      get :query_pallet
      get :new_output_box
      get :output_box
      get :new_input_house
      get :confirm_input_house
      get :input_house
      get :switch_move_pallet
    end
    member do
      get :by_nfe
      get :output_house
      get :new_input_box
      get :input_box
    end
  end
  # match "/palletizing_pallets/query_pallet", :controller => "palletizing_pallets", :action => "query_pallet", via: [:get]

  # resources :breakdown_nfe_xmls

  resources :conference_breakdowns do
    member do
      get :finish
    end
  end

  resources :conference_items do
    member do
      patch :update
    end
  end

  resources :conferences do
    member do
      get :correction
      get :finish_conference
      post :add_item
      delete :destroy_item
    end
  end

  resources :addresses_houses do
    collection do
      get :do_occupe
      get :do_vacate
      get :houses
      post :generator
    end
  end
  resources :houses do

  end
  resources :floors do
    collection do
      get :get_floors_by_street
    end
  end
  resources :streets do
    collection do
      get :get_streets_by_deposit
    end
  end

  resources :deposits do
    collection do
      get :get_deposits_by_warehouse
    end
  end
  resources :warehouses
  resources :checkins do
    member do
      get :checkout
    end
    collection do
      get :search
      get :sup_input
      get :sup_boarding
    end
  end
  resources :driver_restrictions do
    member do
      get :unlock
    end
  end

  resources :vehicle_restrictions do
    member do
      get :unlock
    end
  end

  resources :notifications do
    post :mark_as_read, on: :collection
    get :mark_as_read, on: :member
  end

  resources :brokers

  resources :insurers do
    resources :table_insurances
    resources :policie_insurances
  end

  resources :notfis, only: [:index, :show] do
    collection do
      get :search
    end
  end

  resources :file_edis, only: [:index, :show] do
  collection do
      get :search
      get :select
      post :upload
    end
  end

  resources :edi_occurrences, only: [:index] do
    collection do
      get :search
      get :generate_file
    end
  end

  resources :clients_pallets

  match "/phones", :controller => "static_pages", :action => "phones", via: [:get]
  match "/table_freights/get_calc_freight_minimum", :controller => "table_freights", :action => "get_calc_freight_minimum", via: [:get]
  match '/calculate_liquidity', :controller => 'static_pages', :action => 'calculate_liquidity', via: [:get, :post]
  match "/stretch_routes/get_stretch_route_by_id", :controller => "stretch_routes", :action => "get_stretch_route_by_id", via: [:get]
  match "/stretch_routes/get_stretch_route_by_state", :controller => "stretch_routes", :action => "get_stretch_route_by_state", via: [:get]
  match "/stretch_routes/get_stretch_route_by_state_source_ant_target", :controller => "stretch_routes", :action => "get_stretch_route_by_state_source_ant_target", via: [:get]

  resources :table_freights do
    collection do
      get :calculate_liquidity
    end
  end

  resources :table_icms do
    collection do
      get :search
    end
  end

  resources :antts_vehicles

  resources :antts do
    resources :antts_vehicles
  end

  resources :micro_regions do
    resources :micro_regions_cities
  end

  resources :meetings do
    resources :subjects do
      resources :subject_answers
    end
  end

  resources :action_inspectors, only: [:index, :edit, :update]

  resources :advance_moneys

  match "/get_stretch_routes_from_client_cnpj", :controller => "stretch_routes", :action => "get_stretch_routes_from_client_cnpj", via: [:get]
  match "/get_client_table_price_of_by_client_cnpj_and_stretch_route", :controller => "client_table_prices", :action => "get_client_table_price_of_by_client_cnpj_and_stretch_route", via: [:get]
  match "/get_client_table_price_of_client", :controller => "client_table_prices", :action => "get_client_table_price_of_client", via: [:get]
  match "/get_client_table_price_of_client_service", :controller => "client_table_prices", :action => "get_client_table_price_of_client_service", via: [:get]

  resources :nature_freights

  resources :segments

  resources :promoters

  resources :stretch_routes

  resources :stretches

  resources :tasks do
    collection do
      get :search
    end
    member do
      get :start
      get :finish
      post :add_tasks_users
    end
  end

  match "list_input_scheduling" => "input_controls#list_input_scheduling",  via: [:get]
  match "list_ordem_service_scheduling" => "ordem_services#list_ordem_service_scheduling",  via: [:get]

  resources :companies, only: [:edit, :update, :show]

  resources :config_systems

  resources :client_representatives

  resources :representatives

  resources :offer_drivers do
    member do
      get :confirmed
      get :reject_form
      patch :reject
      get :noshow
      get :nonsuit
      get :reject_observation
    end
  end

  resources :offer_charges do
    collection do
      get :search
    end
  end

  resources :breakdowns

  resources :schedulings do
    collection do
      get :search
    end
  end

  #match :stock_equipaments, :as => :stock_equipaments,  via: [:get]
  match :stock_equipaments,  to: 'stock_equipaments#index',  via: [:get]

  resources :transfer_equipaments, only: [:new] do
    collection do
      post :create
    end
  end

  resources :control_pallet_internals do
    member do
      get :term_pallet
    end
  end

  resources :direct_charges do
    member do
      get :finish_typing
      get :select_nfe
      post :create_ordem_service
      get :add_nfe_xml
      put :attach_xml
    end
  end

  resources :input_controls do
    resources :breakdowns
    resources :breakdown_input_controls do
      get :product
      post :update_product, on: :collection
    end

    resources :breakdown_nfe_xmls

    # resources :nfe_xmls do
    #   resources :breakdown_nfe_xmls
    # end

    resources :conferences do
      resources :conference_breakdowns do
        get :finish
      end
      resources :conference_items
      collection do
        get :approved_last
      end
    end
    member do
      get :admin_show
      get :analize_and_finish
      get :start_conference
      get :review_conference
      get :items
      # get :has_avaria
      get :update_has_avaria
      get :report_team
      put :update_report_team
      get :documents
      patch :documents, to: 'input_controls#documents_upload'
      delete :documents, to: 'input_controls#documents_destroy'
      get 'select_nfe'
      get 'select_pallets'
      post 'create_ordem_service'
      post 'create_stok_pallets'
      get 'finish_typing'
      get 'quitter'
      get :comments
      get :question
      get :printing
      get :print_blind
      get :print_products
      get :print_products_conference
      get :tag
      get :start
      patch :update_start
      get :received
      patch :confirm_received
      get :list_nfe_xmls
      # patch :confirm_qtde_pallets
      get :reschedule
      patch :update_reschedule
      get :add_nfe_xml
      put :attach_xml
    end
    collection do
      get :sup_search
      get :search
      get :oper
      get :sup
      get :admin
    end

    get :received_weight, on: :collection
    get :received_weight_search, on: :collection

    resources :palletizings

  end

  #match '/select_xml_nfe_new_ordem_services', :controller => 'new_ordem_services', :action => 'select_xml_nfe', via: [:get, :post]
  resources :new_creation_ordem_services do
    get :select_xml_nfe, on: :collection
    post :process_xml_nfe, on: :collection
  end

  resources :sealingwaxes

  resources :boardings do
    #resources :sealingwaxes
    resources :breakdown_boardings
    member do
      get :report_team
      put :update_report_team
      get :print
      get :comments
      get :request_pallet
      post :requisition
      get :letter_freight
      get :confirmed
      patch :update_confirmed
      get :start
      patch :update_start
      get :checkin
      patch :update_checkin
      get :detail
      post :request_payment
      get :declined
    end
    collection do
      get :search
      get :sup_search
      get :oper
      get :sup
    end
    resources :boarding_items do
      post :update_row_order, on: :collection
    end
    resources :boarding_vehicles do
      #code
    end
    #match :cancellation, :as => :cancellation, :via => [:get, :put]
    get :selection_shipment_search, on: :collection
    get :payment_discharge_client, on: :collection

  end

  resources :boarding_items do
    post :update_row_order, on: :collection
    match :update_status, :as => :update_status, :via => [:get, :put]
  end

  resources :lower_payables, only: [:destroy] do
    get :quitter, on: :member
  end
  resources :lower_receivables, only: [:destroy] do
    get :quitter, on: :member
  end

  resources :account_receivables do
    member do
      get 'lower'
      post 'pay'
    end
    get :received_driver, on: :collection
    collection do
      get :search
      post :lower_all
    end
  end

  resources :account_payables do
    member do
      get 'lower'
      post 'pay'
      get :send_mail
      #delete 'lower_payable/id'
    end
    collection do
      get 'cost_centers'
      get :search
    end
  end

  get '/print_inventory/:id', to: 'reports#print_inventory', as: 'print_inventory'

app/helpers/input_controls_helper.rb
module InputControlsHelper

  def select_status_input_control
    ([["Aberto", 0],["Recebido", 1], ["Fechado", 2], ["Faturado", 3], ["Dig.Finalizada",4], ["Descarregando",5]])
  end

  def select_equipamento
    ([["NOTA_FISCAL", 0],["PALETE", 1], ["CINTA", 2], ["CHAPATEX", 3]])
  end

  def select_team #ver final do arquivo
    ([["IMBATIVEIS", 1],["UNIDOS VENCEREMOS", 2], ["DIARISTA", 3]])
  end

  def select_dock
    ([["1", 1],["2", 2], ["3", 3], ["4", 4], ["5", 5], ["6", 6], ["7", 7]])
  end

  def select_hangar
    ([["1", 1],["2", 2],["3", 3]])
  end

  def link_to_ordem_service(number, chave)
		nfe_key = NfeKey.where(nfe_type: 'OrdemService', chave: chave)
		if nfe_key.present?
      link_to number, nfe_key.first.ordem_service
		else
			number
		end
  end

  def get_chave(id)
    nfe_xml = NfeXml.where(id: id)
    if nfe_xml.first.chave.present?
      nfe_xml.first.chave
    else
      nfe_xml.first.asset_file_name
    end
  end

  def calculation_discharge(value)
    value = 0.00 # if value.nil?
    value_discharge = ConfigSystem.where(config_key: 'VALUE_DISCHARGE_OPERATION').first
    calc = value * (value_discharge.config_value.to_f / 1000)
    number_to_currency(calc, precision: 2, unit: "R$ ", separator: ",", delimiter: ".")
  end

  def input_stretch_route(client_id)
    #client = Client.where(cpf_cnpj: params[:cpf_cnpj]).first
    client = Client.where(id: client_id).first
    StretchRoute.where(id: client.client_table_prices.select(:stretch_route_id).uniq.pluck(:stretch_route_id))
  end

  def input_type_service(client_id, stretch_route_id )
    #StretchRoute.where(id: client.client_table_prices.select(:stretch_route_id).uniq.pluck(:stretch_route_id))
    type_service_ids = ClientTablePrice.select(:type_service_id).where(client_id: client_id, stretch_route_id: stretch_route_id).pluck(:type_service_id)
    TypeService.where(id: type_service_ids)
  end

  def input_items_button(input_control)

    return link_to 'Iniciar Recebimento', start_input_control_path(input_control), class: "btn btn-blue btn-xs btn-one-click" if input_control.status == InputControl::TypeStatus::FINISH_TYPING

    if input_control.status == InputControl::TypeStatus::DISCHARGE
      return link_to 'Iniciar Conferencia', start_conference_input_control_path(input_control), class: "btn btn-blue btn-xs btn-one-click" if input_control.conferences.count < 2
    end

    #when status was conference
    if current_user.has_role? :oper
      if input_control.status == InputControl::TypeStatus::CONFERENCE
        if input_control.conferences.last.status == "start"
          return link_to 'Items da Conferencia', items_input_control_path(input_control), class: "btn btn-blue btn-xs btn-one-click" if input_control.conferences.count == 1
          return link_to 'Revisar', review_conference_input_control_path(input_control), class: "btn btn-warning btn-xs btn-one-click" if input_control.conferences.count == 2
          return  "<span class=\"text-danger\">Aguardando supervisor</span>".html_safe  if input_control.conferences.last.approved == "waiting"
        else
          # test when approved
          if input_control.conferences.last.approved == "yes"
            if input_control.avaria.nil?
              has_avaria = link_to 'Existe avaria, quero informar', update_has_avaria_input_control_path(input_control, has_avaria: true), class: "btn btn-primary btn-xs btn-one-click"
              has_avaria += link_to 'Não tem avaria', update_has_avaria_input_control_path(input_control, has_avaria: false), class: "btn btn-danger btn-xs btn-one-click", style: "margin-left:5px"
              return has_avaria
              # return link_to 'Tem avaria?', has_avaria_input_control_path(input_control), class: "btn btn-blue btn-xs"
            elsif input_control.avaria
              if input_control.date_finish_avaria.nil?
                conference = input_control.conferences.order(id: :asc).last
                return link_to 'Informar Avaria', input_control_conference_conference_breakdowns_path(input_control, conference), class: "btn btn-blue btn-xs btn-one-click"
              else
                return link_to 'Confirmar Recebimento', received_input_control_path(input_control), class: "btn btn-blue btn-xs btn-one-click"
              end
            else
              return link_to 'Confirmar Recebimento', received_input_control_path(input_control), class: "btn btn-blue btn-xs btn-one-click"
            end
          end
        end
      end
    end

    if input_control.status == InputControl::TypeStatus::RECEIVED
      return link_to "Iniciar paletização", new_input_control_palletizing_path(input_control), {class: "btn btn-info btn-xs"} if input_control.palletizing.nil? || input_control.palletizing.status == "started"
    end

  end


end

  # Fazer testes com esses helper
  #options_for_select([ "VISA", "MasterCard", "Discover" ], ["VISA", "Discover"])
  #options_for_select([ "Denmark", ["USA", {class: 'bold'}], "Sweden" ], ["USA", "Sweden"])
  #options_for_select([["Dollar", "$", {class: "bold"}], ["Kroner", "DKK", {onclick: "alert('HI');"}]])
  #options_for_select(["Free", "Basic", "Advanced", "Super Platinum"], disabled: "Super Platinum")
  #options_for_select(["Free", "Basic", "Advanced", "Super Platinum"], disabled: ["Advanced", "Super Platinum"])
  #options_for_select(["Free", "Basic", "Advanced", "Super Platinum"], selected: "Free", disabled: "Super Platinum")

app/views/input_controls/sup/_review_conference.html.erb
<%= link_to "Voltar", sup_input_controls_path, class: "btn btn-default " %>
<% if @input_control.conferences.second.present? %>
  <% if @input_control.conferences.second.approved == "not" %>
    <%= link_to "Fazer correção", duplicate_conference_input_control_path, class: "btn btn-primary " if @input_control.conferences.count == 2 %>
  <% end %>
<% end %>
<% if @input_control.conferences.last.approved == "waiting" %>
  <%= link_to "Aprovar conferência", approved_last_input_control_conferences_path(@input_control.id), class: "btn btn-primary" %>
<% end %>

<br><br>

<table class="table table-responsive">
  <thead>
    <tr style="background:#666; color:white">
      <td colspan="3" class="text-center">Itens: </td>
      <td><%= @count_items %></td>
      <td class="<%= @count_items_1 != @count_items ? "bg-red" : "" %>">
        <%= @count_items_1 %>
      </td>
      <% if @conference_item_2.present? %>
        <td class="<%= @count_items_2 != @count_items ? "bg-red" : "" %>">
          <%= @count_items_2 %>
        </td>
      <% end %>

      <% if @conference_item_3.present? %>
        <td class="<%= @count_items_3 != @count_items ? "bg-red" : "" %>">
          <%= @count_items_3 %>
        </td>
        <td></td>
      <% end %>
    </tr>
    <tr style="background:#888; color:white">
      <td colspan="3" class="text-center">Total: </td>
      <td><%= @total_qtde %></td>
      <td class="<%= @total_qtde_1 != @total_qtde ? "bg-red" : "" %>">
        <%= @total_qtde_1 %>
      </td>
      <% if @conference_item_2.present? %>
        <td class="<%= @total_qtde_2 != @total_qtde ? "bg-red" : "" %>">
          <%= @total_qtde_2 %>
        </td>
      <% end %>

      <% if @conference_item_3.present? %>
        <td class="<%= @total_qtde_3 != @total_qtde ? "bg-red" : "" %>">
          <%= @total_qtde_3 %>
        </td>
        <td></td>
      <% end %>
    </tr>

    <tr>
      <th>Cod Produto</th>
      <th>Produto</th>
      <th>Avaria</th>
      <th>QTDE NFE</th>
      <th>QTDE oper</th>
      <% if @conference_item_2.present? %>
        <td>QTDE oper</td>
      <% end %>
      <% if @conference_item_3.present? %>
        <td>QTDE sup</td>
        <td></td>
      <% end %>
    </tr>

  </thead>

  <tbody>
    <% @item_input_controls.each do |cod, qtde| %>
      <% product = Product.where(id: cod).first %>
      <tr>
        <td><%= product.cod_prod %></td>
        <td><%= product.descricao %></td>
        <td class="text-danger"><%= @avaria[cod] %></td>
        <td><%= qtde.to_f %></td>
        <td class="<%= qtde.to_f != @conference_item_1[cod].to_f ? "text-danger" : "text-primary" %>"><%= @conference_item_1[cod].to_f %></td>
        <% if @conference_item_2.present? %>
          <td class="<%= qtde.to_f != @conference_item_2[cod].to_f ? "text-danger" : "text-primary" %>"><%= @conference_item_2[cod].to_f %></td>
        <% end %>

        <% if @conference_item_3.present? %>
          <td class="<%= qtde.to_f != @conference_item_3[cod].to_f ? "text-danger" : "text-primary" %>"><%= @conference_item_3[cod].to_f %></td>
            <td>
              <% if @conference_3.approved != "yes" %>
                <% item = location_item_conference( @conference_3.id, cod) %>
                <% if item.present? %>
                  <% conference_item_3 = @conference_3.conference_items.where(product_id: cod).first %>
                  <%= link_to raw(conference_item_3[:qtde_sup].nil? ? "corrigir" : "corrigir <i class=\"fas fa-check\"></i>"), edit_input_control_conference_conference_item_path(@input_control.id, @conference_3.id,  cod ), class: "btn btn-warning btn-xs" if qtde.to_f != @conference_item_3[cod].to_f %>
                <% else %>
                  <%= link_to raw("<i class='fas fa-plus'></i> <span class='hidden-xs'>ítem</span>"), items_input_control_path(@input_control), class: "btn btn-success btn-xs" %>
                <% end %>
              <% end %>
            </td>
        <% end %>
      </tr>
    <% end %>
    <% if @count_items_1 > @count_items || @count_items_2 > @count_items || @count_items_3 > @count_items %>
      <% if @sobras.present? %>
        <% @sobras[:data].each do |sobra| %>
          <% product = Product.where(id: sobra[:product_id]).first %>
          <tr>
            <td><%= product.cod_prod %></td>
            <td><%= product.descricao %></td>
            <td class="text-danger"><%= @avaria[sobra[:product_id]] %></td>
            <td>0.0</td>
            <td class="<%= sobra[:qtde_oper_1].nil? ? "" : "text-danger" %>"><%= sobra[:qtde_oper_1].nil? ? "0.0" : sobra[:qtde_oper_1].to_f %></td>
            <% if @conference_item_2.present? %>
              <td class="<%= sobra[:qtde_oper_2].nil? ? "" : "text-danger" %>"><%= sobra[:qtde_oper_2].nil? ? "0.0" : sobra[:qtde_oper_2].to_f %></td>
            <% end %>
            <% if @conference_item_3.present? %>
              <td class="<%= sobra[:qtde_oper_3].nil? ? "" : "text-danger" %>"><%= sobra[:qtde_oper_3].nil? ? "0.0" : sobra[:qtde_oper_3].to_f %></td>
              <td><%#= link_to "x", edit_input_control_conference_conference_item_path(@input_control.id, @conference_3.id, ConferenceItem.where(conference_id: @conference_3.id, product_id: cod).first.id),  class: "btn btn-danger btn-xs" if !sobra[:qtde_oper_3].nil? %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>