config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  resources :nfe_xml_devolutions do
    member do
      post :xml_process
    end
  end

  resources :devolutions
  get 'palletizing_pallet_product/index'

  resources :palletizings do
    collection do
      get :select_input_control
    end
    member do
      get :view_mode_change
      patch :update_view_mode
    end
      resources :palletizing_pallets do
        collection do
          get :print
        end
      end
  end

  resources :palletizing_pallets do
    collection do
      get :query_pallet
      get :new_output_box
      get :output_box
      get :new_input_house
      get :confirm_input_house
      get :input_house
      get :switch_move_pallet
    end
    member do
      get :by_nfe
      get :output_house
      get :new_input_box
      get :input_box
    end
  end
  # match "/palletizing_pallets/query_pallet", :controller => "palletizing_pallets", :action => "query_pallet", via: [:get]

  # resources :breakdown_nfe_xmls

  resources :conference_breakdowns do
    member do
      get :finish
    end
  end

  resources :conference_items do
    member do
      patch :update
    end
  end

  resources :conferences do
    member do
      get :correction
      get :finish_conference
      post :add_item
      delete :destroy_item
    end
  end

  resources :addresses_houses do
    collection do
      get :do_occupe
      get :do_vacate
      get :houses
      post :generator
    end
  end
  resources :houses do

  end
  resources :floors do
    collection do
      get :get_floors_by_street
    end
  end
  resources :streets do
    collection do
      get :get_streets_by_deposit
    end
  end

  resources :deposits do
    collection do
      get :get_deposits_by_warehouse
    end
  end
  resources :warehouses
  resources :checkins do
    member do
      get :checkout
    end
    collection do
      get :search
      get :sup_input
      get :sup_boarding
    end
  end
  resources :driver_restrictions do
    member do
      get :unlock
    end
  end

  resources :vehicle_restrictions do
    member do
      get :unlock
    end
  end

  resources :notifications do
    post :mark_as_read, on: :collection
    get :mark_as_read, on: :member
  end

  resources :brokers

  resources :insurers do
    resources :table_insurances
    resources :policie_insurances
  end

  resources :notfis, only: [:index, :show] do
    collection do
      get :search
    end
  end

  resources :file_edis, only: [:index, :show] do
  collection do
      get :search
      get :select
      post :upload
    end
  end

  resources :edi_occurrences, only: [:index] do
    collection do
      get :search
      get :generate_file
    end
  end

  resources :clients_pallets

  match "/phones", :controller => "static_pages", :action => "phones", via: [:get]
  match "/table_freights/get_calc_freight_minimum", :controller => "table_freights", :action => "get_calc_freight_minimum", via: [:get]
  match '/calculate_liquidity', :controller => 'static_pages', :action => 'calculate_liquidity', via: [:get, :post]
  match "/stretch_routes/get_stretch_route_by_id", :controller => "stretch_routes", :action => "get_stretch_route_by_id", via: [:get]
  match "/stretch_routes/get_stretch_route_by_state", :controller => "stretch_routes", :action => "get_stretch_route_by_state", via: [:get]
  match "/stretch_routes/get_stretch_route_by_state_source_ant_target", :controller => "stretch_routes", :action => "get_stretch_route_by_state_source_ant_target", via: [:get]

  resources :table_freights do
    collection do
      get :calculate_liquidity
    end
  end

  resources :table_icms do
    collection do
      get :search
    end
  end

  resources :antts_vehicles

  resources :antts do
    resources :antts_vehicles
  end

  resources :micro_regions do
    resources :micro_regions_cities
  end

  resources :meetings do
    resources :subjects do
      resources :subject_answers
    end
  end

  resources :action_inspectors, only: [:index, :edit, :update]

  resources :advance_moneys

  match "/get_stretch_routes_from_client_cnpj", :controller => "stretch_routes", :action => "get_stretch_routes_from_client_cnpj", via: [:get]
  match "/get_client_table_price_of_by_client_cnpj_and_stretch_route", :controller => "client_table_prices", :action => "get_client_table_price_of_by_client_cnpj_and_stretch_route", via: [:get]
  match "/get_client_table_price_of_client", :controller => "client_table_prices", :action => "get_client_table_price_of_client", via: [:get]
  match "/get_client_table_price_of_client_service", :controller => "client_table_prices", :action => "get_client_table_price_of_client_service", via: [:get]

  resources :nature_freights

  resources :segments

  resources :promoters

  resources :stretch_routes

  resources :stretches

  resources :tasks do
    collection do
      get :search
    end
    member do
      get :start
      get :finish
      post :add_tasks_users
    end
  end

  match "list_input_scheduling" => "input_controls#list_input_scheduling",  via: [:get]
  match "list_ordem_service_scheduling" => "ordem_services#list_ordem_service_scheduling",  via: [:get]

  resources :companies, only: [:edit, :update, :show]

  resources :config_systems

  resources :client_representatives

  resources :representatives

  resources :offer_drivers do
    member do
      get :confirmed
      get :reject_form
      patch :reject
      get :noshow
      get :nonsuit
      get :reject_observation
    end
  end

  resources :offer_charges do
    collection do
      get :search
    end
  end

  resources :breakdowns

  resources :schedulings do
    collection do
      get :search
    end
  end

  #match :stock_equipaments, :as => :stock_equipaments,  via: [:get]
  match :stock_equipaments,  to: 'stock_equipaments#index',  via: [:get]

  resources :transfer_equipaments, only: [:new] do
    collection do
      post :create
    end
  end

  resources :control_pallet_internals do
    member do
      get :term_pallet
    end
  end

  resources :direct_charges do
    member do
      get :finish_typing
      get :select_nfe
      post :create_ordem_service
      get :add_nfe_xml
      put :attach_xml
    end
  end

  resources :input_controls do
    resources :breakdowns
    resources :breakdown_input_controls do
      get :product
      post :update_product, on: :collection
    end

    resources :breakdown_nfe_xmls

    # resources :nfe_xmls do
    #   resources :breakdown_nfe_xmls
    # end

    resources :conferences do
      resources :conference_breakdowns do
        get :finish
      end
      resources :conference_items
      collection do
        get :approved_last
      end
    end
    member do
      get :admin_show
      get :analize_and_finish
      get :start_conference
      get :review_conference
      get :items
      # get :has_avaria
      get :update_has_avaria
      get :report_team
      put :update_report_team
      get :documents
      patch :documents, to: 'input_controls#documents_upload'
      delete :documents, to: 'input_controls#documents_destroy'
      get 'select_nfe'
      get 'select_pallets'
      post 'create_ordem_service'
      post 'create_stok_pallets'
      get 'finish_typing'
      get 'quitter'
      get :comments
      get :question
      get :printing
      get :print_blind
      get :print_products
      get :print_products_conference
      get :tag
      get :start
      patch :update_start
      get :received
      patch :confirm_received
      get :list_nfe_xmls
      # patch :confirm_qtde_pallets
      get :reschedule
      patch :update_reschedule
      get :add_nfe_xml
      put :attach_xml
    end
    collection do
      get :sup_search
      get :search
      get :oper
      get :sup
      get :admin
    end

    get :received_weight, on: :collection
    get :received_weight_search, on: :collection

    resources :palletizings

  end

  #match '/select_xml_nfe_new_ordem_services', :controller => 'new_ordem_services', :action => 'select_xml_nfe', via: [:get, :post]
  resources :new_creation_ordem_services do
    get :select_xml_nfe, on: :collection
    post :process_xml_nfe, on: :collection
  end

  resources :sealingwaxes

  resources :boardings do
    #resources :sealingwaxes
    resources :breakdown_boardings
    member do
      get :report_team
      put :update_report_team
      get :print
      get :comments
      get :request_pallet
      post :requisition
      get :letter_freight
      get :confirmed
      patch :update_confirmed
      get :start
      patch :update_start
      get :checkin
      patch :update_checkin
      get :detail
      post :request_payment
      get :declined
    end
    collection do
      get :search
      get :sup_search
      get :oper
      get :sup
    end
    resources :boarding_items do
      post :update_row_order, on: :collection
    end
    resources :boarding_vehicles do
      #code
    end
    #match :cancellation, :as => :cancellation, :via => [:get, :put]
    get :selection_shipment_search, on: :collection
    get :payment_discharge_client, on: :collection

  end

  resources :boarding_items do
    post :update_row_order, on: :collection
    match :update_status, :as => :update_status, :via => [:get, :put]
  end

  resources :lower_payables, only: [:destroy] do
    get :quitter, on: :member
  end
  resources :lower_receivables, only: [:destroy] do
    get :quitter, on: :member
  end

  resources :account_receivables do
    member do
      get 'lower'
      post 'pay'
    end
    get :received_driver, on: :collection
    collection do
      get :search
      post :lower_all
    end
  end

  resources :account_payables do
    member do
      get 'lower'
      post 'pay'
      get :send_mail
      #delete 'lower_payable/id'
    end
    collection do
      get 'cost_centers'
      get :search
    end
  end

  get '/print_inventory/:id', to: 'reports#print_inventory', as: 'print_inventory'

app/models/vehicle_restriction.rb
class VehicleRestriction < ApplicationRecord
  belongs_to :vehicle, required: false
  validates :vehicle_id, presence: true
  validates :motive_id, presence: true

  enum motive_id: { suitable_floor: 0, overweight: 1 }
  enum status: { locking: 0, unlocking: 1}

  before_save do |v|
    v.status = 0
  end

  def self.vehicle_loking?(vehicle_id)
    VehicleRestriction.locking.where(vehicle_id: vehicle_id).present?
  end

  def self.unlock(vehicle_restriction)
    VehicleRestriction.where(id: vehicle_restriction.id).update_all(status: 1)
  end

  def self.check_places_loking?(places)
    positivo = false
    places.each do |place|
      vehicle = Vehicle.where(placa: place).first
      if vehicle.blank?
        positivo = false
        return positivo
      else
        positivo = VehicleRestriction.vehicle_loking?(vehicle.id)
        return positivo
      end
    end
    positivo
  end

end

# placa cavalo - tem Restricao
# placa carreta - não tem restricao

# se a placa não existe sai do loop
# assim que achar a restrição no primeiro item sair do loop

app/controllers/vehicle_restrictions_controller.rb
class VehicleRestrictionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_vehicle, only: [:show], execept: [:unlock]
  load_and_authorize_resource


  def index
    @vehicle_restrictions = VehicleRestriction.locking
  end

  def show

  end

  def new
    @vehicle_restriction = VehicleRestriction.new
    @vehicle = Vehicle.find(params[:vehicle_id])
  end

  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
    @vehicle_restriction = VehicleRestriction.new(vehicle_restriction_params)
    @vehicle_restriction.vehicle_id = @vehicle.id
    respond_to do |format|
      if @vehicle_restriction.save
        format.html { redirect_to dashboard_sup_path, flash: { success: "Vehicle Restriction was successfully locked." } }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def unlock
    @vehicle_restriction = VehicleRestriction.find(params[:id])
    VehicleRestriction.unlock(@vehicle_restriction)
    respond_to do |format|
      format.html { redirect_to vehicle_restrictions_path, flash: { success: "Vehicle Restriction was successfully unlocked." } }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      #@vehicle_restriction = VehicleRestriction.find(params[:id])
      @vehicle_restriction = VehicleRestriction.first
      vehicle = @vehicle_restriction.vehicle
      #@vehicle = Vehicle.where(@vehicle_restriction.vehicle).first
    end

    def vehicle_restriction_params
      params.require(:vehicle_restriction).permit(:vehicle_id, :motive_id, :motive_observation)
    end
end

app/helpers/vehicle_restriction_helper.rb
module VehicleRestrictionHelper
end

app/helpers/vehicle_restrictions_helper.rb
module VehicleRestrictionsHelper
end

app/views/vehicle_restrictions/_form.html.erb
<%= form_for(@vehicle_restriction) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= hidden_field_tag "vehicle_id", @vehicle.id %>

  <div class="form-group">
    <%= label_tag :place, "Placa" %><br>
    <%= text_field_tag :place, @vehicle.placa, class: "form-control", style: 'text-transform:uppercase' %>
  </div>

  <div class="form-group">
    <%= f.label :motive_id, "Motivo" %><br>
    <%= f.select(:motive_id, options_for_select(VehicleRestriction.motive_ids.keys.to_a.map{ |w| [w.humanize, w] }), {include_blank: false}, class: "form-control") %>
  </div>

  <div class="form-group">
    <%= f.label :motive_observation, "Observacao" %><br>
    <%= f.text_area :motive_observation, class: "form-control" %>
  </div>

  <div id="vehicle_placa_result">

  </div>

  <div class="form-group">
    <%= f.submit "Salvar", class: "btn btn-blue" %>
    <%#= link_to "Exibir",  vehicle_path(@vehicle), class: "btn btn-info" if !@vehicle.new_record? %>
    <%#= link_to "Listar Todos", vehicles_path, class: "btn btn-default" %>
  </div>

<% end  %>

app/views/vehicle_restrictions/_vehicle.html.erb
<p>
  <strong>Placa:</strong>
  <%= vehicle.placa %>
</p>

<p>
  <strong>Capacidade:</strong>
  <%= vehicle.capacity %>
</p>

app/views/vehicle_restrictions/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Listagem de Veiculos Bloqueados</div>
  <div class="panel-body">
    <%#= link_to 'Novo Veículos', new_vehicle_path, class: "btn btn-blue btn-lg btn-block" %>
    <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Placa</th>
            <th>Tipo</th>
            <th>Tipo veiculo</th>
            <th>No.Eixo</th>
            <th>Qtde Pallets</th>
            <th>Piso</th>
            <th>Motorista</th>
            <th>Proprietário</th>
            <th colspan="3">Opções</th>
          </tr>
        </thead>

        <tbody>
          <% @vehicle_restrictions.each do |vehicle_restriction| %>
            <tr>
              <td><%= vehicle_restriction.vehicle.place_state %></td>
              <td><%= vehicle_restriction.vehicle.tipo_nome if vehicle_restriction.vehicle.tipo.present? %></td>
              <td><%= vehicle_restriction.vehicle.tipo_veiculo_nome %></td>
              <td align="center"><%= vehicle_restriction.vehicle.numero_eixos %></td>
              <td><%= "#{vehicle_restriction.vehicle.qtde_paletes}" %></td>
              <td><%= vehicle_restriction.vehicle.tipo_piso_assoalho_nome if vehicle_restriction.vehicle.tipo_piso_assoalho.present? %></td>
              <td><%= vehicle_restriction.vehicle.drivers.first.nome  if vehicle_restriction.vehicle.drivers.present? %></td>
              <td><%= vehicle_restriction.vehicle.owners.first.fantasia  if vehicle_restriction.vehicle.owners.present? %></td>
              <td>
                <%= link_to unlock_vehicle_restriction_path(vehicle_restriction) do %>
                  <i class="fas fa-unlock notification"></i>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/vehicle_restrictions/new.html.erb
<h1>New Vehicle Restriction</h1>

<%= render 'form' %>

app/views/vehicle_restrictions/show.html.erb
<%= render(:partial => 'vehicle', locals: {vehicle: @vehicle_restriction.vehicle})  %>

<%#= render(:partial => 'motive', locals: {vehicle: @vehicle_restriction.motive})  %>

<%= link_to lock_vehicle_restriction_path() do %>
  <i class="fas fa-lock notification"></i>
<% end %>